import { AuthProvider } from "@/providers/AuthProvider";
import { GeolocationProvider } from "@/providers/GeolocationProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.className} h-full antialiased`}>
      <body className="h-full min-h-full">
        <GeolocationProvider>
          <AuthProvider>
            {children}
            <Toaster position="bottom-right" reverseOrder={true} />
          </AuthProvider>
        </GeolocationProvider>
      </body>
    </html>
  );
}
